// Constantes para el Flujo Unificado Global
export const SERVICES = {
  TRANSPORT: 'transport',
  DELIVERY: 'delivery',
  MANDADO: 'mandado',
  ENVIO: 'envio'
} as const;

export type ServiceType = typeof SERVICES[keyof typeof SERVICES];

export const ROLES = {
  CUSTOMER: 'customer',
  DRIVER: 'driver'
} as const;

export type FlowRole = typeof ROLES[keyof typeof ROLES];

// Enum para tipos de viaje
export enum RideType {
  NORMAL = 'normal',
  FOR_OTHER = 'for_other'
}

// Nomenclatura estandarizada con prefijos globales
export const FLOW_STEPS = {
  // Selection steps
  SELECCION_SERVICIO: 'SELECCION_SERVICIO',

  // Customer Transport steps
  CUSTOMER_TRANSPORT_DEFINICION_VIAJE: 'CUSTOMER_TRANSPORT_DEFINICION_VIAJE',
  CUSTOMER_TRANSPORT_CONFIRM_ORIGIN: 'CUSTOMER_TRANSPORT_CONFIRM_ORIGIN',
  CUSTOMER_TRANSPORT_CONFIRM_DESTINATION: 'CUSTOMER_TRANSPORT_CONFIRM_DESTINATION',
  CUSTOMER_TRANSPORT_SELECCION_VEHICULO: 'CUSTOMER_TRANSPORT_SELECCION_VEHICULO',
  CUSTOMER_TRANSPORT_METODOLOGIA_PAGO: 'CUSTOMER_TRANSPORT_METODOLOGIA_PAGO',
  CUSTOMER_TRANSPORT_BUSCANDO_CONDUCTOR: 'CUSTOMER_TRANSPORT_BUSCANDO_CONDUCTOR',
  CUSTOMER_TRANSPORT_CONFIRMAR_CONDUCTOR: 'CUSTOMER_TRANSPORT_CONFIRMAR_CONDUCTOR',
  CUSTOMER_TRANSPORT_ESPERANDO_ACEPTACION: 'CUSTOMER_TRANSPORT_ESPERANDO_ACEPTACION',
  CUSTOMER_TRANSPORT_ELECCION_CONDUCTOR: 'CUSTOMER_TRANSPORT_ELECCION_CONDUCTOR', // Mantener para compatibilidad
  CUSTOMER_TRANSPORT_GESTION_CONFIRMACION: 'CUSTOMER_TRANSPORT_GESTION_CONFIRMACION',
  CUSTOMER_TRANSPORT_DURANTE_FINALIZACION: 'CUSTOMER_TRANSPORT_DURANTE_FINALIZACION',

  // Driver Transport steps
  DRIVER_TRANSPORT_RECIBIR_SOLICITUD: 'DRIVER_TRANSPORT_RECIBIR_SOLICITUD',
  DRIVER_TRANSPORT_ACEPTAR_RECHAZAR: 'DRIVER_TRANSPORT_ACEPTAR_RECHAZAR',
  DRIVER_TRANSPORT_EN_CAMINO_ORIGEN: 'DRIVER_TRANSPORT_EN_CAMINO_ORIGEN',
  DRIVER_TRANSPORT_EN_ORIGEN: 'DRIVER_TRANSPORT_EN_ORIGEN',
  DRIVER_TRANSPORT_INICIAR_VIAJE: 'DRIVER_TRANSPORT_INICIAR_VIAJE',
  DRIVER_TRANSPORT_EN_VIAJE: 'DRIVER_TRANSPORT_EN_VIAJE',
  DRIVER_TRANSPORT_COMPLETAR_VIAJE: 'DRIVER_TRANSPORT_COMPLETAR_VIAJE',

  // Customer Delivery steps
  CUSTOMER_DELIVERY_BUSQUEDA_NEGOCIO: 'CUSTOMER_DELIVERY_BUSQUEDA_NEGOCIO',
  CUSTOMER_DELIVERY_ARMADO_PEDIDO: 'CUSTOMER_DELIVERY_ARMADO_PEDIDO',
  CUSTOMER_DELIVERY_CHECKOUT_CONFIRMACION: 'CUSTOMER_DELIVERY_CHECKOUT_CONFIRMACION',
  CUSTOMER_DELIVERY_SEGUIMIENTO_DELIVERY: 'CUSTOMER_DELIVERY_SEGUIMIENTO_DELIVERY',

  // Driver Delivery steps
  DRIVER_DELIVERY_RECIBIR_SOLICITUD: 'DRIVER_DELIVERY_RECIBIR_SOLICITUD',
  DRIVER_DELIVERY_PREPARAR_PEDIDO: 'DRIVER_DELIVERY_PREPARAR_PEDIDO',
  DRIVER_DELIVERY_RECOGER_PEDIDO: 'DRIVER_DELIVERY_RECOGER_PEDIDO',
  DRIVER_DELIVERY_EN_CAMINO_ENTREGA: 'DRIVER_DELIVERY_EN_CAMINO_ENTREGA',
  DRIVER_DELIVERY_ENTREGAR_PEDIDO: 'DRIVER_DELIVERY_ENTREGAR_PEDIDO',

  // Customer Mandado steps
  CUSTOMER_MANDADO_DETALLES_MANDADO: 'CUSTOMER_MANDADO_DETALLES_MANDADO',
  CUSTOMER_MANDADO_PRECIO_PAGO: 'CUSTOMER_MANDADO_PRECIO_PAGO',
  CUSTOMER_MANDADO_BUSCANDO_CONDUCTOR: 'CUSTOMER_MANDADO_BUSCANDO_CONDUCTOR',
  CUSTOMER_MANDADO_COMUNICACION_CONFIRMACION: 'CUSTOMER_MANDADO_COMUNICACION_CONFIRMACION',
  CUSTOMER_MANDADO_FINALIZACION: 'CUSTOMER_MANDADO_FINALIZACION',

  // Driver Mandado steps
  DRIVER_MANDADO_RECIBIR_SOLICITUD: 'DRIVER_MANDADO_RECIBIR_SOLICITUD',
  DRIVER_MANDADO_EN_CAMINO_ORIGEN: 'DRIVER_MANDADO_EN_CAMINO_ORIGEN',
  DRIVER_MANDADO_RECOGER_PRODUCTOS: 'DRIVER_MANDADO_RECOGER_PRODUCTOS',
  DRIVER_MANDADO_EN_CAMINO_DESTINO: 'DRIVER_MANDADO_EN_CAMINO_DESTINO',
  DRIVER_MANDADO_ENTREGAR_MANDADO: 'DRIVER_MANDADO_ENTREGAR_MANDADO',

  // Customer Envío steps
  CUSTOMER_ENVIO_DETALLES_ENVIO: 'CUSTOMER_ENVIO_DETALLES_ENVIO',
  CUSTOMER_ENVIO_CALCULAR_PRECIO: 'CUSTOMER_ENVIO_CALCULAR_PRECIO',
  CUSTOMER_ENVIO_SEGUIMIENTO_PAQUETE: 'CUSTOMER_ENVIO_SEGUIMIENTO_PAQUETE',
  CUSTOMER_ENVIO_CONFIRMACION_ENTREGA: 'CUSTOMER_ENVIO_CONFIRMACION_ENTREGA',

  // Driver Envío steps
  DRIVER_ENVIO_RECIBIR_SOLICITUD: 'DRIVER_ENVIO_RECIBIR_SOLICITUD',
  DRIVER_ENVIO_EN_CAMINO_ORIGEN: 'DRIVER_ENVIO_EN_CAMINO_ORIGEN',
  DRIVER_ENVIO_RECOGER_PAQUETE: 'DRIVER_ENVIO_RECOGER_PAQUETE',
  DRIVER_ENVIO_EN_CAMINO_DESTINO: 'DRIVER_ENVIO_EN_CAMINO_DESTINO',
  DRIVER_ENVIO_ENTREGAR_PAQUETE: 'DRIVER_ENVIO_ENTREGAR_PAQUETE'
} as const;

export type FlowStep = typeof FLOW_STEPS[keyof typeof FLOW_STEPS];

// Configuración de servicios disponibles
export const AVAILABLE_SERVICES = [
  {
    id: SERVICES.TRANSPORT,
    title: 'Transporte',
    subtitle: 'Viajes en carro o moto',
    icon: '🚗',
    description: 'Viajes seguros y cómodos'
  },
  {
    id: SERVICES.DELIVERY,
    title: 'Delivery',
    subtitle: 'Comida y productos',
    icon: '🍕',
    description: 'Delivery de restaurantes y comercios'
  },
  {
    id: SERVICES.MANDADO,
    title: 'Mandado',
    subtitle: 'Servicios personales',
    icon: '🛒',
    description: 'Compras y encargos personales'
  },
  {
    id: SERVICES.ENVIO,
    title: 'Envío',
    subtitle: 'Paquetes y documentos',
    icon: '📦',
    description: 'Envíos seguros de paquetes'
  }
];

// Flujos por servicio y rol
export const SERVICE_FLOWS = {
  // Customer flows
  customer: {
    [SERVICES.TRANSPORT]: [
      FLOW_STEPS.CUSTOMER_TRANSPORT_DEFINICION_VIAJE,
      FLOW_STEPS.CUSTOMER_TRANSPORT_CONFIRM_DESTINATION, // Para viajes normales
      // CONFIRM_ORIGIN se agrega condicionalmente para viajes "otro"
      FLOW_STEPS.CUSTOMER_TRANSPORT_SELECCION_VEHICULO,
      FLOW_STEPS.CUSTOMER_TRANSPORT_METODOLOGIA_PAGO,
      FLOW_STEPS.CUSTOMER_TRANSPORT_BUSCANDO_CONDUCTOR,
      FLOW_STEPS.CUSTOMER_TRANSPORT_CONFIRMAR_CONDUCTOR,
      FLOW_STEPS.CUSTOMER_TRANSPORT_ESPERANDO_ACEPTACION,
      FLOW_STEPS.CUSTOMER_TRANSPORT_DURANTE_FINALIZACION
    ] as FlowStep[],
    [SERVICES.DELIVERY]: [
      FLOW_STEPS.CUSTOMER_DELIVERY_BUSQUEDA_NEGOCIO,
      FLOW_STEPS.CUSTOMER_DELIVERY_ARMADO_PEDIDO,
      FLOW_STEPS.CUSTOMER_DELIVERY_CHECKOUT_CONFIRMACION,
      FLOW_STEPS.CUSTOMER_DELIVERY_SEGUIMIENTO_DELIVERY
    ] as FlowStep[],
    [SERVICES.MANDADO]: [
      FLOW_STEPS.CUSTOMER_MANDADO_DETALLES_MANDADO,
      FLOW_STEPS.CUSTOMER_MANDADO_PRECIO_PAGO,
      FLOW_STEPS.CUSTOMER_MANDADO_BUSCANDO_CONDUCTOR,
      FLOW_STEPS.CUSTOMER_MANDADO_COMUNICACION_CONFIRMACION,
      FLOW_STEPS.CUSTOMER_MANDADO_FINALIZACION
    ] as FlowStep[],
    [SERVICES.ENVIO]: [
      FLOW_STEPS.CUSTOMER_ENVIO_DETALLES_ENVIO,
      FLOW_STEPS.CUSTOMER_ENVIO_CALCULAR_PRECIO,
      FLOW_STEPS.CUSTOMER_ENVIO_SEGUIMIENTO_PAQUETE,
      FLOW_STEPS.CUSTOMER_ENVIO_CONFIRMACION_ENTREGA
    ] as FlowStep[]
  },
  // Driver flows
  driver: {
    [SERVICES.TRANSPORT]: [
      FLOW_STEPS.DRIVER_TRANSPORT_RECIBIR_SOLICITUD,
      FLOW_STEPS.DRIVER_TRANSPORT_ACEPTAR_RECHAZAR,
      FLOW_STEPS.DRIVER_TRANSPORT_EN_CAMINO_ORIGEN,
      FLOW_STEPS.DRIVER_TRANSPORT_EN_ORIGEN,
      FLOW_STEPS.DRIVER_TRANSPORT_INICIAR_VIAJE,
      FLOW_STEPS.DRIVER_TRANSPORT_EN_VIAJE,
      FLOW_STEPS.DRIVER_TRANSPORT_COMPLETAR_VIAJE
    ] as FlowStep[],
    [SERVICES.DELIVERY]: [
      FLOW_STEPS.DRIVER_DELIVERY_RECIBIR_SOLICITUD,
      FLOW_STEPS.DRIVER_DELIVERY_PREPARAR_PEDIDO,
      FLOW_STEPS.DRIVER_DELIVERY_RECOGER_PEDIDO,
      FLOW_STEPS.DRIVER_DELIVERY_EN_CAMINO_ENTREGA,
      FLOW_STEPS.DRIVER_DELIVERY_ENTREGAR_PEDIDO
    ] as FlowStep[],
    [SERVICES.MANDADO]: [
      FLOW_STEPS.DRIVER_MANDADO_RECIBIR_SOLICITUD,
      FLOW_STEPS.DRIVER_MANDADO_EN_CAMINO_ORIGEN,
      FLOW_STEPS.DRIVER_MANDADO_RECOGER_PRODUCTOS,
      FLOW_STEPS.DRIVER_MANDADO_EN_CAMINO_DESTINO,
      FLOW_STEPS.DRIVER_MANDADO_ENTREGAR_MANDADO
    ] as FlowStep[],
    [SERVICES.ENVIO]: [
      FLOW_STEPS.DRIVER_ENVIO_RECIBIR_SOLICITUD,
      FLOW_STEPS.DRIVER_ENVIO_EN_CAMINO_ORIGEN,
      FLOW_STEPS.DRIVER_ENVIO_RECOGER_PAQUETE,
      FLOW_STEPS.DRIVER_ENVIO_EN_CAMINO_DESTINO,
      FLOW_STEPS.DRIVER_ENVIO_ENTREGAR_PAQUETE
    ] as FlowStep[]
  }
} as const;
