import type { MapFlowStep, StepConfig } from "./types";

type ConfigRecord = Record<MapFlowStep, StepConfig>;

export const DEFAULT_CONFIG: ConfigRecord = {
  idle: {
    id: "idle",
    bottomSheet: {
      visible: false,
      minHeight: 0,
      maxHeight: 0,
      initialHeight: 0,
      showHandle: false,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "none", duration: 0 },
  },
  travel_start: {
    id: "travel_start",
    bottomSheet: {
      visible: true,
      minHeight: 140,
      maxHeight: 420,
      initialHeight: 200,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  set_locations: {
    id: "set_locations",
    bottomSheet: {
      visible: true,
      minHeight: 160,
      maxHeight: 520,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  confirm_origin: {
    id: "confirm_origin",
    bottomSheet: {
      visible: true,
      minHeight: 100,
      maxHeight: 260,
      initialHeight: 120,
      showHandle: true,
      allowDrag: false,
      allowClose: false,
    },
    mapInteraction: "pan_to_confirm",
    transition: { type: "fade", duration: 180 },
  },
  choose_service: {
    id: "choose_service",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 560,
      initialHeight: 440,
      showHandle: true,
      allowDrag: true,
      allowClose: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  choose_driver: {
    id: "choose_driver",
    bottomSheet: {
      visible: true,
      minHeight: 160,
      maxHeight: 520,
      initialHeight: 380,
      showHandle: true,
      allowDrag: true,
      allowClose: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  summary: {
    id: "summary",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 520,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
      allowClose: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "slide", duration: 220 },
  },
  SELECCION_SERVICIO: {
    id: "SELECCION_SERVICIO",
    bottomSheet: {
      visible: true,
      minHeight: 140,
      maxHeight: 420,
      initialHeight: 200,
      showHandle: true,
      allowDrag: true,
      allowClose: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_DISPONIBILIDAD: {
    id: "DRIVER_DISPONIBILIDAD",
    bottomSheet: {
      visible: true,
      minHeight: 120,
      maxHeight: 360,
      initialHeight: 160,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "fade", duration: 180 },
  },
  DRIVER_FINALIZACION_RATING: {
    id: "DRIVER_FINALIZACION_RATING",
    bottomSheet: {
      visible: true,
      minHeight: 260,
      maxHeight: 640,
      initialHeight: 480,
      showHandle: true,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_TRANSPORT_DEFINICION_VIAJE: {
    id: "CUSTOMER_TRANSPORT_DEFINICION_VIAJE",
    bottomSheet: {
      visible: true,
      minHeight: 160,
      maxHeight: 520,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_TRANSPORT_CONFIRM_ORIGIN: {
    id: "CUSTOMER_TRANSPORT_CONFIRM_ORIGIN",
    bottomSheet: {
      visible: false,
      minHeight: 0,
      maxHeight: 0,
      initialHeight: 0,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "pan_to_confirm",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_TRANSPORT_CONFIRM_DESTINATION: {
    id: "CUSTOMER_TRANSPORT_CONFIRM_DESTINATION",
    bottomSheet: {
      visible: false,
      minHeight: 0,
      maxHeight: 0,
      initialHeight: 0,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "pan_to_confirm",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_TRANSPORT_SELECCION_VEHICULO: {
    id: "CUSTOMER_TRANSPORT_SELECCION_VEHICULO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 560,
      initialHeight: 440,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_TRANSPORT_METODOLOGIA_PAGO: {
    id: "CUSTOMER_TRANSPORT_METODOLOGIA_PAGO",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 520,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_TRANSPORT_BUSCANDO_CONDUCTOR: {
    id: "CUSTOMER_TRANSPORT_BUSCANDO_CONDUCTOR",
    bottomSheet: {
      visible: true,
      minHeight: 300,
      maxHeight: 700,
      initialHeight: 500,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_TRANSPORT_CONFIRMAR_CONDUCTOR: {
    id: "CUSTOMER_TRANSPORT_CONFIRMAR_CONDUCTOR",
    bottomSheet: {
      visible: true,
      minHeight: 160,
      maxHeight: 420,
      initialHeight: 240,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_TRANSPORT_ESPERANDO_ACEPTACION: {
    id: "CUSTOMER_TRANSPORT_ESPERANDO_ACEPTACION",
    bottomSheet: {
      visible: true,
      minHeight: 140,
      maxHeight: 360,
      initialHeight: 180,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_TRANSPORT_ELECCION_CONDUCTOR: {
    id: "CUSTOMER_TRANSPORT_ELECCION_CONDUCTOR",
    bottomSheet: {
      visible: true,
      minHeight: 160,
      maxHeight: 520,
      initialHeight: 380,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_TRANSPORT_GESTION_CONFIRMACION: {
    id: "CUSTOMER_TRANSPORT_GESTION_CONFIRMACION",
    bottomSheet: {
      visible: true,
      minHeight: 100,
      maxHeight: 260,
      initialHeight: 120,
      showHandle: true,
      allowDrag: false,
    },
    mapInteraction: "pan_to_confirm",
    transition: { type: "fade", duration: 180 },
  },
  CUSTOMER_TRANSPORT_DURANTE_FINALIZACION: {
    id: "CUSTOMER_TRANSPORT_DURANTE_FINALIZACION",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 520,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_TRANSPORT_CONDUCTOR_LLEGO: {
    id: "CUSTOMER_TRANSPORT_CONDUCTOR_LLEGO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 400,
      initialHeight: 300,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_TRANSPORT_VIAJE_EN_CURSO: {
    id: "CUSTOMER_TRANSPORT_VIAJE_EN_CURSO",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_driver",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_TRANSPORT_VIAJE_COMPLETADO: {
    id: "CUSTOMER_TRANSPORT_VIAJE_COMPLETADO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 600,
      initialHeight: 400,
      showHandle: true,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_TRANSPORT_VIAJE_CANCELADO: {
    id: "CUSTOMER_TRANSPORT_VIAJE_CANCELADO",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 250,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_DELIVERY_BUSQUEDA_NEGOCIO: {
    id: "CUSTOMER_DELIVERY_BUSQUEDA_NEGOCIO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 560,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_DELIVERY_ARMADO_PEDIDO: {
    id: "CUSTOMER_DELIVERY_ARMADO_PEDIDO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 560,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_DELIVERY_CHECKOUT_CONFIRMACION: {
    id: "CUSTOMER_DELIVERY_CHECKOUT_CONFIRMACION",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 520,
      initialHeight: 320,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_DELIVERY_SEGUIMIENTO_DELIVERY: {
    id: "CUSTOMER_DELIVERY_SEGUIMIENTO_DELIVERY",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_driver",
    transition: { type: "fade", duration: 200 },
  },
  // Driver Transport Steps
  DRIVER_TRANSPORT_RECIBIR_SOLICITUD: {
    id: "DRIVER_TRANSPORT_RECIBIR_SOLICITUD",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_TRANSPORT_ACEPTAR_RECHAZAR: {
    id: "DRIVER_TRANSPORT_ACEPTAR_RECHAZAR",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_TRANSPORT_EN_CAMINO_ORIGEN: {
    id: "DRIVER_TRANSPORT_EN_CAMINO_ORIGEN",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 400,
      initialHeight: 250,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_TRANSPORT_EN_ORIGEN: {
    id: "DRIVER_TRANSPORT_EN_ORIGEN",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 400,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_TRANSPORT_INICIAR_VIAJE: {
    id: "DRIVER_TRANSPORT_INICIAR_VIAJE",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_TRANSPORT_EN_VIAJE: {
    id: "DRIVER_TRANSPORT_EN_VIAJE",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_TRANSPORT_COMPLETAR_VIAJE: {
    id: "DRIVER_TRANSPORT_COMPLETAR_VIAJE",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_TRANSPORT_VIAJE_COMPLETADO: {
    id: "DRIVER_TRANSPORT_VIAJE_COMPLETADO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 600,
      initialHeight: 400,
      showHandle: true,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_TRANSPORT_VIAJE_CANCELADO: {
    id: "DRIVER_TRANSPORT_VIAJE_CANCELADO",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 250,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  // Driver Delivery Steps
  DRIVER_DELIVERY_RECIBIR_SOLICITUD: {
    id: "DRIVER_DELIVERY_RECIBIR_SOLICITUD",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_DELIVERY_PREPARAR_PEDIDO: {
    id: "DRIVER_DELIVERY_PREPARAR_PEDIDO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_DELIVERY_RECOGER_PEDIDO: {
    id: "DRIVER_DELIVERY_RECOGER_PEDIDO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_DELIVERY_EN_CAMINO_ENTREGA: {
    id: "DRIVER_DELIVERY_EN_CAMINO_ENTREGA",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_DELIVERY_ENTREGAR_PEDIDO: {
    id: "DRIVER_DELIVERY_ENTREGAR_PEDIDO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  // Customer Mandado Steps
  CUSTOMER_MANDADO_DETALLES_MANDADO: {
    id: "CUSTOMER_MANDADO_DETALLES_MANDADO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 600,
      initialHeight: 400,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_MANDADO_PRECIO_PAGO: {
    id: "CUSTOMER_MANDADO_PRECIO_PAGO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_MANDADO_BUSCANDO_CONDUCTOR: {
    id: "CUSTOMER_MANDADO_BUSCANDO_CONDUCTOR",
    bottomSheet: {
      visible: true,
      minHeight: 300,
      maxHeight: 700,
      initialHeight: 500,
      showHandle: false,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_MANDADO_COMUNICACION_CONFIRMACION: {
    id: "CUSTOMER_MANDADO_COMUNICACION_CONFIRMACION",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_MANDADO_FINALIZACION: {
    id: "CUSTOMER_MANDADO_FINALIZACION",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 600,
      initialHeight: 400,
      showHandle: true,
      allowDrag: false,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  // Driver Mandado Steps
  DRIVER_MANDADO_RECIBIR_SOLICITUD: {
    id: "DRIVER_MANDADO_RECIBIR_SOLICITUD",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_MANDADO_EN_CAMINO_ORIGEN: {
    id: "DRIVER_MANDADO_EN_CAMINO_ORIGEN",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_MANDADO_RECOGER_PRODUCTOS: {
    id: "DRIVER_MANDADO_RECOGER_PRODUCTOS",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_MANDADO_EN_CAMINO_DESTINO: {
    id: "DRIVER_MANDADO_EN_CAMINO_DESTINO",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_MANDADO_ENTREGAR_MANDADO: {
    id: "DRIVER_MANDADO_ENTREGAR_MANDADO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  // Customer Envio Steps
  CUSTOMER_ENVIO_DETALLES_ENVIO: {
    id: "CUSTOMER_ENVIO_DETALLES_ENVIO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 600,
      initialHeight: 400,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_ENVIO_CALCULAR_PRECIO: {
    id: "CUSTOMER_ENVIO_CALCULAR_PRECIO",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  CUSTOMER_ENVIO_SEGUIMIENTO_PAQUETE: {
    id: "CUSTOMER_ENVIO_SEGUIMIENTO_PAQUETE",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  CUSTOMER_ENVIO_CONFIRMACION_ENTREGA: {
    id: "CUSTOMER_ENVIO_CONFIRMACION_ENTREGA",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  // Driver Envio Steps
  DRIVER_ENVIO_RECIBIR_SOLICITUD: {
    id: "DRIVER_ENVIO_RECIBIR_SOLICITUD",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_ENVIO_EN_CAMINO_ORIGEN: {
    id: "DRIVER_ENVIO_EN_CAMINO_ORIGEN",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_ENVIO_RECOGER_PAQUETE: {
    id: "DRIVER_ENVIO_RECOGER_PAQUETE",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
  DRIVER_ENVIO_EN_CAMINO_DESTINO: {
    id: "DRIVER_ENVIO_EN_CAMINO_DESTINO",
    bottomSheet: {
      visible: true,
      minHeight: 180,
      maxHeight: 350,
      initialHeight: 220,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "follow_route",
    transition: { type: "fade", duration: 200 },
  },
  DRIVER_ENVIO_ENTREGAR_PAQUETE: {
    id: "DRIVER_ENVIO_ENTREGAR_PAQUETE",
    bottomSheet: {
      visible: true,
      minHeight: 200,
      maxHeight: 500,
      initialHeight: 300,
      showHandle: true,
      allowDrag: true,
    },
    mapInteraction: "none",
    transition: { type: "slide", duration: 220 },
  },
};  